CREATE TABLE product
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    description character varying(255) NOT NULL
);

ALTER TABLE product
    ADD CONSTRAINT product_pkey PRIMARY KEY (id);

CREATE TABLE public.order_product (
    order_id bigint NOT NULL,
    product_id bigint NOT NULL
);

ALTER TABLE public.order_product
    ADD CONSTRAINT pk_order_product PRIMARY KEY (order_id, product_id)